export const defaultState = {
  imageUpload: {
    imagePath: {},
    sheetSnap: ['20%'],
  },
  agePicker: {
    label: 'Age',
    age: '',
    ageArray: [10, 20, 30, 40, 50, 60, 70],
    sheetSnap: ['60%'],
    placeholder: 'Select Age',
    error: '',
    onChangeError: 'something went wrong',
  },
  name: {
    value: '@hkrhasan',
    edit: false,
    error: '',
    onChangeError: 'name is required',
  },
  firstName: {
    label: 'First Name',
    value: '',
    error: '',
    maxLength: 8,
    minLength: 0,
    minLengthError: 'FirstName must be 8 characters',
    onChangeError: 'something went wrong',
  },
  phone: {
    value: '',
    error: '',
    length: 10,
    label: 'Phone',
    onChangeError: 'something went wrong',
  },
  country: {
    data: [
      {label: 'India', value: 'india'},
      {label: 'China', value: 'china'},
      {label: 'Pakistan', value: 'pakistan'},
      {label: 'USA', value: 'usa'},
    ],
    value: null,
    label: 'Select country',
    zIndex: 10,
    error: '',
    onChangeError: 'something went wrong',
  },
  state: {
    data: [
      {label: 'Delhi', value: 'delhi'},
      {label: 'Chennai', value: 'Chennai'},
      {label: 'Mumbai', value: 'Mumbai'},
      {label: 'Punjab', value: 'Punjab'},
    ],
    values: [],
    label: 'Select States',
    error: '',
    onChangeError: 'something went wrong',
  },
  about: {
    value: '',
    error: '',
    label: 'About Us',
    onChangeError: 'something went wrong',
  },
  radios: {
    data: [
      {id: 1, label: 'Male', selected: true},
      {id: 2, label: 'Female', selected: false},
      {id: 3, label: 'Others', selected: false},
    ],
    label: 'Gender',
    error: '',
    onChangeError: 'something went wrong',
  },
  quantity: {
    value: 0,
    min: 0,
    max: 10,
    label: 'Quantity',
    error: '',
    onChangeError: 'something went wrong',
  },
  date: {
    value: '',
    defaultValue: '',
    placeholder: 'dd-mm-yyyy',
    dateFormat: 'dd-MM-yyyy',
    label: 'DOB',
    error: '',
    onChangeError: 'something went wrong',
  },
  slider: {
    sliderValue: {value: 0.2},
    error: '',
    onChangeError: 'something went wrong',
  },
  checks: {
    data: [
      {title: 'I agree', checked: true},
      {title: 'I agree', checked: false},
    ],
    error: '',
    onChangeError: 'something went wrong',
  },
  modal: {
    isVisible: false,
  },
};
